[package]
name = "redscript-cache-compact"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
anyhow = "1"
argh = "0.1"
vmap = "0.6"

[dependencies.redscript-io]
git = "https://github.com/jac3km4/redscript"
rev = "v1.0.0-preview6"
features = ["mmap"]
